target("test_graph")
    add_cxxflags("-stdlib=libc++ ", {tools = "clang++"})
    set_kind("binary")
    add_files("test_graph.cpp")
    add_includedirs("..")

target("test_matrix")
    add_cxxflags("-stdlib=libc++ ", {tools = "clang++"})
    set_kind("binary")
    add_files("test_matrix.cpp")
    add_includedirs("..")
