package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "my_binary",
    srcs = ["my_test.cpp"],
    deps = [
        "@opencv4//:core",
        "@opencv4//:highgui",
        "@opencv4//:imgcodecs",
        "@opencv4//:imgproc",
    ],
)

